const treatmentMenu = [
    {
    id: 1,
    category: "massages",
    title: "FIRE & ICE STONE CBD MASSAGE",
    img: "drinks",
    desc: `This stimulating massage with CBD oil uses a combination of cool jade stones and warm volcanic stones to rejuvenate and relieve deep muscle tension. The cooling effects of jade reduce inflammation, while the warm stones ease muscles and soothe aches and pains. This signature service begins with a welcoming foot ritual and concludes with a deeply relaxing scalp massage. `,
    price: "Monday–Thursday $345 / Friday–Sunday $355",
    },
    {
    id: 2,
    category: "massages",
    title: "THERAPEUTIC MASSAGE",
    img: "drinks",
    desc: `This stimulating massage with CBD oil uses a combination of cool jade stones and warm volcanic stones to rejuvenate and relieve deep muscle tension. The cooling effects of jade reduce inflammation, while the warm stones ease muscles and soothe aches and pains. This signature service begins with a welcoming foot ritual and concludes with a deeply relaxing scalp massage. `,
    price: "Monday–Thursday $345 / Friday–Sunday $355",
    },
    {
    id: 3,
    category: "massages",
    title: "AROMATHERAPY MASSAGE",
    img: "drinks",
    desc: `This stimulating massage with CBD oil uses a combination of cool jade stones and warm volcanic stones to rejuvenate and relieve deep muscle tension. The cooling effects of jade reduce inflammation, while the warm stones ease muscles and soothe aches and pains. This signature service begins with a welcoming foot ritual and concludes with a deeply relaxing scalp massage. `,
    price: "Monday–Thursday $345 / Friday–Sunday $355",
    },
    {
    id: 4,
    category: "massages",
    title: "PRENATAL MASSAGE",
    img: "drinks",
    desc: `This stimulating massage with CBD oil uses a combination of cool jade stones and warm volcanic stones to rejuvenate and relieve deep muscle tension. The cooling effects of jade reduce inflammation, while the warm stones ease muscles and soothe aches and pains. This signature service begins with a welcoming foot ritual and concludes with a deeply relaxing scalp massage. `,
    price: "Monday–Thursday $345 / Friday–Sunday $355",
    },
    {
    id: 5,
    category: "massages",
    title: "COUPLES MASSAGE",
    img: "drinks",
    desc: `This stimulating massage with CBD oil uses a combination of cool jade stones and warm volcanic stones to rejuvenate and relieve deep muscle tension. The cooling effects of jade reduce inflammation, while the warm stones ease muscles and soothe aches and pains. This signature service begins with a welcoming foot ritual and concludes with a deeply relaxing scalp massage. `,
    price: "Monday–Thursday $345 / Friday–Sunday $355",
    },
    {
    id: 6,
    category: "skincare",
    title: "hydrating & brightening facial",
    img: "drinks",
    desc: `This stimulating massage with CBD oil uses a combination of cool jade stones and warm volcanic stones to rejuvenate and relieve deep muscle tension. The cooling effects of jade reduce inflammation, while the warm stones ease muscles and soothe aches and pains. This signature service begins with a welcoming foot ritual and concludes with a deeply relaxing scalp massage. `,
    price: "Monday–Thursday $345 / Friday–Sunday $355",
    },
    {
    id: 7,
    category: "skincare",
    title: "texture balance + oil control facial",
    img: "drinks",
    desc: `This stimulating massage with CBD oil uses a combination of cool jade stones and warm volcanic stones to rejuvenate and relieve deep muscle tension. The cooling effects of jade reduce inflammation, while the warm stones ease muscles and soothe aches and pains. This signature service begins with a welcoming foot ritual and concludes with a deeply relaxing scalp massage. `,
    price: "Monday–Thursday $345 / Friday–Sunday $355",
    },
    {
    id: 8,
    category: "skincare",
    title: "pore extraction and acne facial",
    img: "drinks",
    desc: `This stimulating massage with CBD oil uses a combination of cool jade stones and warm volcanic stones to rejuvenate and relieve deep muscle tension. The cooling effects of jade reduce inflammation, while the warm stones ease muscles and soothe aches and pains. This signature service begins with a welcoming foot ritual and concludes with a deeply relaxing scalp massage. `,
    price: "Monday–Thursday $345 / Friday–Sunday $355",
    },
    {
    id: 9,
    category: "skincare",
    title: "anti-aging red LED therapy",
    img: "drinks",
    desc: `This stimulating massage with CBD oil uses a combination of cool jade stones and warm volcanic stones to rejuvenate and relieve deep muscle tension. The cooling effects of jade reduce inflammation, while the warm stones ease muscles and soothe aches and pains. This signature service begins with a welcoming foot ritual and concludes with a deeply relaxing scalp massage. `,
    price: "Monday–Thursday $345 / Friday–Sunday $355",
    },
    {
    id: 10,
    category: "skincare",
    title: "COUPLES MASSAGE",
    img: "drinks",
    desc: `This stimulating massage with CBD oil uses a combination of cool jade stones and warm volcanic stones to rejuvenate and relieve deep muscle tension. The cooling effects of jade reduce inflammation, while the warm stones ease muscles and soothe aches and pains. This signature service begins with a welcoming foot ritual and concludes with a deeply relaxing scalp massage. `,
    price: "Monday–Thursday $345 / Friday–Sunday $355",
    },
    {
    id: 11,
    category: "haircare",
    title: "THERAPEUTIC MASSAGE",
    img: "drinks",
    desc: `This stimulating massage with CBD oil uses a combination of cool jade stones and warm volcanic stones to rejuvenate and relieve deep muscle tension. The cooling effects of jade reduce inflammation, while the warm stones ease muscles and soothe aches and pains. This signature service begins with a welcoming foot ritual and concludes with a deeply relaxing scalp massage. `,
    price: "Monday–Thursday $345 / Friday–Sunday $355",
    },
    {
    id: 12,
    category: "haircare",
    title: "AROMATHERAPY MASSAGE",
    img: "drinks",
    desc: `This stimulating massage with CBD oil uses a combination of cool jade stones and warm volcanic stones to rejuvenate and relieve deep muscle tension. The cooling effects of jade reduce inflammation, while the warm stones ease muscles and soothe aches and pains. This signature service begins with a welcoming foot ritual and concludes with a deeply relaxing scalp massage. `,
    price: "Monday–Thursday $345 / Friday–Sunday $355",
    },
    {
    id: 13,
    category: "haircare",
    title: "PRENATAL MASSAGE",
    img: "drinks",
    desc: `This stimulating massage with CBD oil uses a combination of cool jade stones and warm volcanic stones to rejuvenate and relieve deep muscle tension. The cooling effects of jade reduce inflammation, while the warm stones ease muscles and soothe aches and pains. This signature service begins with a welcoming foot ritual and concludes with a deeply relaxing scalp massage. `,
    price: "Monday–Thursday $345 / Friday–Sunday $355",
    },
    {
    id: 14,
    category: "haircare",
    title: "COUPLES MASSAGE",
    img: "drinks",
    desc: `This stimulating massage with CBD oil uses a combination of cool jade stones and warm volcanic stones to rejuvenate and relieve deep muscle tension. The cooling effects of jade reduce inflammation, while the warm stones ease muscles and soothe aches and pains. This signature service begins with a welcoming foot ritual and concludes with a deeply relaxing scalp massage. `,
    price: "Monday–Thursday $345 / Friday–Sunday $355",
    },
    {
    id: 15,
    category: "gentlemen",
    title: "for grooms - wedding day prep",
    img: "drinks",
    desc: `This stimulating massage with CBD oil uses a combination of cool jade stones and warm volcanic stones to rejuvenate and relieve deep muscle tension. The cooling effects of jade reduce inflammation, while the warm stones ease muscles and soothe aches and pains. This signature service begins with a welcoming foot ritual and concludes with a deeply relaxing scalp massage. `,
    price: "Monday–Thursday $345 / Friday–Sunday $355",
    },
    {
    id: 16,
    category: "gentlemen",
    title: "anti-aging facial",
    img: "drinks",
    desc: `This stimulating massage with CBD oil uses a combination of cool jade stones and warm volcanic stones to rejuvenate and relieve deep muscle tension. The cooling effects of jade reduce inflammation, while the warm stones ease muscles and soothe aches and pains. This signature service begins with a welcoming foot ritual and concludes with a deeply relaxing scalp massage. `,
    price: "Monday–Thursday $345 / Friday–Sunday $355",
    },
    {
    id: 17,
    category: "gentlemen",
    title: "PRENATAL MASSAGE",
    img: "drinks",
    desc: `This stimulating massage with CBD oil uses a combination of cool jade stones and warm volcanic stones to rejuvenate and relieve deep muscle tension. The cooling effects of jade reduce inflammation, while the warm stones ease muscles and soothe aches and pains. This signature service begins with a welcoming foot ritual and concludes with a deeply relaxing scalp massage. `,
    price: "Monday–Thursday $345 / Friday–Sunday $355",
    },
    {
    id: 18,
    category: "gentlemen",
    title: "COUPLES MASSAGE",
    img: "drinks",
    desc: `This stimulating massage with CBD oil uses a combination of cool jade stones and warm volcanic stones to rejuvenate and relieve deep muscle tension. The cooling effects of jade reduce inflammation, while the warm stones ease muscles and soothe aches and pains. This signature service begins with a welcoming foot ritual and concludes with a deeply relaxing scalp massage. `,
    price: "Monday–Thursday $345 / Friday–Sunday $355",
    },
]


